// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using metrica_back.src.Data;

#nullable disable

namespace metrica_back.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260403162200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("metrica_back.src.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d018eb5-f880-42ac-a94b-f93353876657"),
                            CreatedAt = new DateTime(2026, 3, 4, 16, 21, 58, 160, DateTimeKind.Utc).AddTicks(7928),
                            Email = "john.doe@example.com",
                            PasswordHash = "$2a$11$cSAFA9SmdNo5ZuCrtGORmOA01ci/io7InsH3op7RlEVBL0msBJwyG",
                            UserName = "john_doe"
                        });
                });

            modelBuilder.Entity("metrica_back.src.Models.Website", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackingCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Websites");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5911306-77a3-40cd-8729-5b7b68d125b5"),
                            CreatedAt = new DateTime(2026, 3, 29, 16, 21, 58, 496, DateTimeKind.Utc).AddTicks(1155),
                            Domain = "shop.example.com",
                            Name = "Интернет-магазин",
                            TrackingCode = 1,
                            UserId = new Guid("5d018eb5-f880-42ac-a94b-f93353876657")
                        },
                        new
                        {
                            Id = new Guid("27187291-8a48-4b5a-8e3a-5781b14f256b"),
                            CreatedAt = new DateTime(2026, 3, 30, 16, 21, 58, 496, DateTimeKind.Utc).AddTicks(1652),
                            Domain = "blog.example.com",
                            Name = "Блог",
                            TrackingCode = 2,
                            UserId = new Guid("5d018eb5-f880-42ac-a94b-f93353876657")
                        });
                });

            modelBuilder.Entity("metrica_back.src.Models.Website", b =>
                {
                    b.HasOne("metrica_back.src.Models.User", "User")
                        .WithMany("Websites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("metrica_back.src.Models.User", b =>
                {
                    b.Navigation("Websites");
                });
#pragma warning restore 612, 618
        }
    }
}
